"""Added date column to schedules

Revision ID: c1f37423d1a4
Revises: 5d866fe1c6f1
Create Date: 2024-10-08 11:06:45.874691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f37423d1a4'
down_revision = '5d866fe1c6f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.alter_column('userId',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.alter_column('userId',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('date')

    # ### end Alembic commands ###
